### ISSUE TITLE
LipsNet-L implementation in K_Net Forward

### ISSUE THREAD

**Issue by ahanjaya** [jerry99s/LipsNet#1]
https://github.com/jerry99s/LipsNet/blob/732b87c58947d5414009f9576e14d5b9c30119a9/lipsnet.py#L42

Hi, I'm trying to use LipsNet-L and found the implementation has slightly difference with the paper. In the paper, it's mentioned for the K network will have softplus activation. Could you please clarify if there's any mistake in this regard? Thanks.

**Comment by xjsong99** [comment]
Sorry for the late reply!

In the paper, the K network does have a softplus activation.
When you define the network, the parameter _k_out_act_ should be set as _nn.Softplus_.
`net = LipsNet(k_out_act=nn.Softplus, ...)`

Now, in the 91 line in _lipsnet.py_, the default value of _k_out_act_ has been changed from _nn.Identity_ to _nn.Softplus_.
https://github.com/jerry99s/LipsNet/blob/8859ff2c84740fc1469e6f7f401586e73a058ab1/lipsnet.py#L90-L92
